script: bundle exec rake SPEC_OPTS="--tag ~travis" spec
before_script: bundle exec rake ci:before
language: ruby
services: mysql
rvm:
  - jruby-1.7.18
#  - jruby-head
#  - jruby-head-d20
#  - jruby-head-d21
jdk:
  - openjdk6
  - openjdk7
matrix:
  exclude:
#    - rvm: jruby-head
#      jdk: openjdk6
#    - rvm: jruby-head-d20
#      jdk: openjdk6
#    - rvm: jruby-head-d21
#      jdk: openjdk6
